language: node_js

node_js:
  - 13

cache:
  directories:
    - node_modules

script:
  - CI=false npm run build
  - mv build server

deploy:
  - provider: script
    script: sh scripts/deploy.sh
    skip_cleanup: true
    on:
      branch: master
